server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/v2/users/**

        - id: user-notification
          uri: lb://USER-NOTIFICATION
          predicates:
            - Path=/user-notification/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
