server:
  port: 8080 # Порт API Gateway

spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: order-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/orders/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
      access: read-only