server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}
  management:
    endpoints:
      web:
        exposure:
          include: "*"
        base-path: /actuator
    endpoint:
      gateway:
        enabled: true
      health:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
